### ISSUE TITLE
error on ubuntu 14.

### ISSUE THREAD

**Issue by jamengual** [jsmartin/ansible-graphite#1]
Hi I just tried your playbook on ubuntu 14 and I get :+1: 

TASK: [jmartin.graphite | apt_repository repo='ppa:jmartin-1/tools'] *********\* 
<localhost> REMOTE_MODULE apt_repository repo='ppa:jmartin-1/tools'
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1406158539.73-64342075785403 && echo $HOME/.ansible/tmp/ansible-tmp-1406158539.73-64342075785403']
<localhost> PUT /tmp/tmpn2VOrx TO /root/.ansible/tmp/ansible-tmp-1406158539.73-64342075785403/apt_repository
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1406158539.73-64342075785403/apt_repository; rm -rf /root/.ansible/tmp/ansible-tmp-1406158539.73-64342075785403/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1406158539.73-64342075785403/apt_repository", line 1510, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1406158539.73-64342075785403/apt_repository", line 408, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://ppa.launchpad.net/jmartin-1/tools/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
, E:Some index files failed to download. They have been ignored, or old ones used instead.

FATAL: all hosts have already failed -- aborting

ubuntu 14 not supported ?

Thanks.

**Comment by jlhughes** [comment]
Hi, I'd like to install into Ubuntu 14 as well.

**Comment by felixfischer** [comment]
+1

**Comment by Ajibola** [comment]
+1

**Comment by drusellers** [comment]
+1

**Comment by jtmoulia** [comment]
+1

Looks like packages were only built for [precise](http://ppa.launchpad.net/jmartin-1/tools/ubuntu/dists/precise/main/binary-amd64/Packages), no [trusty](http://ppa.launchpad.net/jmartin-1/tools/ubuntu/dists/trusty/main/binary-amd64/Packages).

**Comment by mtekel** [comment]
+1
